FROM node:20-bullseye-slim

WORKDIR /app

COPY package.json ./
COPY prisma ./prisma
RUN npm install --workspaces=false

COPY tsconfig.json ./
COPY src ./src
COPY scripts ./scripts

CMD ["npx", "tsx", "src/scripts/worker.ts"]
